apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tweet-saver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-saver
  template:
    spec:
      containers:
        - name: tweet-saver
          image: ghcr.io/dvdblk/tweet-saver:v1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
            name: env-var-secret
