apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tweet-saver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-saver
  template:
    metadata:
      labels:
        app: tweet-saver
    spec:
      containers:
        - name: tweet-saver
          image: ghcr.io/dvdblk/tweet-saver:v1.1.3
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: env-var-secret
